# coding=utf-8
import os
SERVER_HOST = 'localhost'
SERVER_PORT = '80'

SESSION_COOKIE_NAME = "CarpeDiem"
COOKIE_SECRET_KEY = bytes.fromhex(os.environ.get("FERNET_SESSION_KEY"))
SMS_API = ""

GEO_API_USER_AGENT = "CarpeDiemServer"
GEO_API_RESP_DATA_LANG = 'pl'

FILE_TOKEN_LENGTH = 24
FILE_IMAGE_MAX_SIZE = 5 * 1024 * 1024
FILE_IMAGE_COMPRESSION = 75

DB_NAME = "CarpeDiem"
DB_HOST = os.environ.get("MONGODB_HOST")
DB_PROF_NAME_MAX_LEN = 40
DB_PROF_MIN_USER_AGE = 18
DB_PROF_DESCRIPTION_MAX_LEN = 1024
DB_SELECTING_AGE_DIFF = 2

SMS_SERVICE_TEST_MODE = True
SMS_CODE_LEN = 5
UTILS_GEN_PASSWORD_LENGTH = 8
